In [196]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [197]:
dataset=pd.read_csv('Test_Project_MIS.csv')


In [198]:
#we labelled medium priority as 1
#low priority as 0
priority_mapping = {"Low": 0, "Medium": 1, "High": 2}
dataset["Priority"] = dataset["Priority"].map(priority_mapping)

In [199]:
y=dataset.iloc[:,[7]].values

In [200]:
ppriority_mapping = {"M": 34, "S": 33, "C": 33, "W":33}
dataset["R_Priority"] = dataset["R_Priority"].map(ppriority_mapping)

In [201]:
#in the dataset we encountered that time is minute format we changed it as completely in seconds
def convert_to_seconds(time):
    try:
        minutes = float(time.split()[0])  
        seconds = minutes * 60  
        return int(seconds) 
    except (ValueError, AttributeError):
        return np.nan  


dataset["Time"] = dataset["Time"].apply(convert_to_seconds)


mean_value = dataset["Time"].mean()
dataset["Time"].fillna(mean_value, inplace=True)

In [202]:
x=dataset.iloc[:,[0]+[1]+[2]+[4]+[5]+[6]].values
print(x)

[[1.000e+00 3.300e+01 3.000e+00 3.000e+00 4.800e+02 1.680e+02]
 [2.000e+00 3.300e+01 3.000e+00 3.000e+00 2.400e+02 8.400e+01]
 [3.000e+00 3.300e+01 3.000e+00 3.000e+00 9.000e+01 3.150e+01]
 ...
 [1.312e+03 3.300e+01 3.000e+00 3.000e+00 2.400e+02 8.400e+01]
 [1.313e+03 3.400e+01 1.000e+00 1.000e+00 3.000e+02 3.500e+01]
 [1.314e+03 3.300e+01 3.000e+00 1.000e+00 2.700e+02 3.150e+01]]


In [203]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [204]:
#we used support vector machine because we treated while prioritization it is ok to deal with false postive 
#dealing with false posive can be a postive sign rather leaving the false postive as insignificant
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(x_train, y_train)
predictions = classifier.predict(x_test)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [205]:
#now enter the new dataset that has Bussiness Requirment, Bussiness requirment Prioirty, 
#functional_ priority,time,complexity,cost
data=pd.read_csv('Test_Project_MIS.csv')

In [206]:
priority_mapping = {"Low": 0, "Medium": 1, "High": 2}
data["Priority"] = data["Priority"].map(priority_mapping)

In [207]:
ppriority_mapping = {"M": 34, "S": 33, "C": 33, "W":33}
data["R_Priority"] = data["R_Priority"].map(ppriority_mapping)

In [208]:
def convert_to_seconds(time):
    try:
        minutes = float(time.split()[0])  
        seconds = minutes * 60  
        return int(seconds) 
    except (ValueError, AttributeError):
        return np.nan  


data["Time"] = data["Time"].apply(convert_to_seconds)


mean_value = data["Time"].mean()
data["Time"].fillna(mean_value, inplace=True)

In [209]:
x1=data.iloc[:,[0]+[1]+[2]+[4]+[5]+[6]].values

In [210]:
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(x_train, y_train)
predictions = classifier.predict(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [211]:
print(x1)

[[1.000e+00 3.300e+01 3.000e+00 3.000e+00 4.800e+02 1.680e+02]
 [2.000e+00 3.300e+01 3.000e+00 3.000e+00 2.400e+02 8.400e+01]
 [3.000e+00 3.300e+01 3.000e+00 3.000e+00 9.000e+01 3.150e+01]
 ...
 [1.312e+03 3.300e+01 3.000e+00 3.000e+00 2.400e+02 8.400e+01]
 [1.313e+03 3.400e+01 1.000e+00 1.000e+00 3.000e+02 3.500e+01]
 [1.314e+03 3.300e+01 3.000e+00 1.000e+00 2.700e+02 3.150e+01]]


In [212]:
e=classifier.predict(x1)

In [213]:
#this helps to choose the specific coloumns that need to be there in the output csv file
output_df = pd.DataFrame({"Bussiness_req": data["B_Req"],"Cost":data["Time"],"PrioritizationScore": e})

In [214]:
#this will helps to generate a csv file that contains list of testcases that need to be executed first

output_df.to_csv("output.csv", index=False)

In [215]:
import os

print(os.getcwd())

/content
